name: 'Spark-ui scan adoption script'
description: 'Detects the adoption of the Spark UI in the codebase and generates a report.'
author: 'Adevinta'

# define the gh marketplace branding
branding:
  icon: 'activity'
  color: 'blue'

# Define your inputs here.
inputs:
  configuration:
    description: 'Configuration file for the script.'
    required: false
  output:
    description: 'Output file for the script.'
    required: false
  verbose:
    description: 'Whether to tell the GitHub client to log details of its requests. true or false. Default is to run in debug mode when the GitHub Actions step debug logging is turned on.'
    required: false
  github-token:
    description: 'GitHub token'
    required: true
  debug:
    description: Whether to tell the GitHub client to log details of its requests. true or false. Default is to run in debug mode when the GitHub Actions step debug logging is turned on.
    default: ${{ runner.debug == '1' }}
  details:
    description: 'Whether to include detailed information in the report. true or false. Default is false.'
    required: false
  sort:
    description: 'Whether to sort the report by the number of occurrences of the Spark UI. count or alphabetical. Default is count.'
    required: false
  directory:
    description: 'Directory to scan.'
    required: false
  extensions:
    description: 'Extensions to scan.'
    required: false
  imports:
    description: 'Import patterns to scan.'
    required: false
  datadog-metrics:
    description: 'Datadog'
    required: true
    default: 'false'
  organisation-name:
    description: 'Datadog Organisation name'
    required: false
  authorisation_user:
    description: 'Adevinta Authorisation user'
    required: true
  authorisation_password:
    description: 'Adevinta Authorisation password'
    required: true

# Environment
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm i @spark-ui/cli-utils@beta
      shell: bash
    - name: Run script
      # run: npx @spark-ui/cli-utils scan --config ${{ inputs.configuration }} --token ${{ inputs.github-token }} --debug ${{ inputs.debug }}
      run: |
        echo "Running script with configuration: ${CONFIGURATION}"
        GITHUB_TOKEN=${GITHUB_TOKEN} node ${GITHUB_ACTION_PATH}/dist/index.mjs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DEBUG: ${{ inputs.debug }}
        CONFIGURATION: ${{ inputs.configuration }}
        VERBOSE: ${{ inputs.verbose }}
        DETAILS: ${{ inputs.details }}
        SORT: ${{ inputs.sort }}
        DIRECTORY: ${{ inputs.directory }}
        EXTENSIONS: ${{ inputs.extensions }}
        IMPORTS: ${{ inputs.imports }}
        DATADOG_METRICS: ${{ inputs.datadog-metrics }}
        DATADOG_ORGANISATION_NAME: ${{ inputs.organisation-name }}
        AUTH_USER: ${{ inputs.authorisation_user }}
        AUTH_PASSWORD: ${{ inputs.authorisation_password }}
