name: 'Spark-ui scan adoption script'
description: 'Detects the adoption of the Spark UI in the codebase and generates a report.'
author: 'Adevinta'

# define the gh marketplace branding
branding:
  icon: 'activity'
  color: 'blue'

# Define your inputs here.
inputs:
  configuration:
    description: 'Configuration file for the script.'
    required: false
    default: './spark-ui.json'
  # Define your inputs here.
  who-to-greet:
    description: Who to greet
    required: false
    default: World
  github-token:
    description: 'GitHub token'
    required: true
  debug:
    description: Whether to tell the GitHub client to log details of its requests. true or false. Default is to run in debug mode when the GitHub Actions step debug logging is turned on.
    default: ${{ runner.debug == '1' }}


# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

# Environment
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm i @spark-ui/cli-utils
      shell: bash
    - name: Run script
      # run: npx @spark-ui/cli-utils scan --config ${{ inputs.configuration }} --token ${{ inputs.github-token }} --debug ${{ inputs.debug }}
      run: 'node dist/index.mjs'
      shell: bash