name: 'Spark-ui scan adoption script'
description: 'Detects the adoption of the Spark UI in the codebase and generates a report.'
author: 'Adevinta'

# define the gh marketplace branding
branding:
  icon: 'activity'
  color: 'blue'

# Define your inputs here.
inputs:
  configuration:
    description: 'Configuration file for the script.'
    required: false
    default: './spark-ui.json'
  # Define your inputs here.
  who-to-greet:
    description: Who to greet
    required: false
    default: World
  github-token:
    description: 'GitHub token'
    required: true


# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

# Environment
runs:
  using: 'node20'
  main: 'bin/index.mjs'